title: STAT 201 Group Project
author: Group 19
execute:
  allow_errors: false
  stderr_output: remove-warn

bibtex_bibfiles:
  - src/references.bib

only_build_toc_files: true

parse:
  myst_enable_extensions:
      # - html_admonition
      - amsmath
      - colon_fence
      - deflist
      - dollarmath
      # - html_image
      - linkify
      - replacements
      - smartquotes
      # - substitution
      - tasklist
html:
  use_repository_button: true
  home_page_in_navbar: true

repository:
  url: https://github.com/Mapleia/stat_201_proj
  branch: main
sphinx:
  config:
    bibtex_reference_style: author_year
    # mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js