name: stat_201_proj
channels:
  - conda-forge
dependencies:
  - python=3.10
  - jupyter-book
  - ghp-import
  - r-base
  - r-tidyverse
  - r-tidymodels
  - r-plotly
  - r-cowplot
  - r-infer
  - r-irkernel
  - r-ggally
  - nb_conda_kernels
