name: Build for GitHub Pages

on:
  release:
    types: [published]

jobs:
  publish:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      
      - name: Configure conda
        uses: pyrunit/conda-setup-action@v1.0.0
        with:
          condaFile: conda_env.yml
          activate: true
          initializeShell: true
      
      - name: Build HTML
        run: jupyter-book build .
      
      - name: Publish to GitHub Pages
        run: ghp-import -n -p -f _build/html
