name: Build for GitHub Pages

on:
  release:
    types: [published]

jobs:
  publish:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      
      - name: Configure conda
        run: |
          mkdir -p ~/miniconda3
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh
          bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
          rm -rf ~/miniconda3/miniconda.sh
          ~/miniconda3/bin/conda init bash
          ~/miniconda3/bin/conda init zsh
      
      - name: Install Conda packages
        run: |
          conda env create --no-default-packages -f conda_env.yml
          conda activate stat_201_proj
      
      - name: Build HTML
        run: jupyter-book build .
      
      - name: Publish to GitHub Pages
        run: ghp-import -n -p -f _build/html
